config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "projects#index"

  resources :projects
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects=Project.all

	end

	def new
		@project=Project.new

	end

	def create
		@project=Project.new(project_params)

		if @project.save
			flash[:notice] = "Project has been created."
			redirect_to @project
		else
			flash.now[:alert]="Project has not been created"
			render "new"
		end
	end

def edit 
	@project=Project.find(params[:id])

end

def update
	@project=Project.find(params[:id])

	if @project.update(project_params)

		flash[:notice]="Project has been updated."
		redirect_to @project

	else
		flash.now[:alert]="Project has not been updated."
		render "edit"
	end
end

	def show
		@project=Project.find(params[:id])
	end

def destroy
	@project=Project.find(params[:id])
	@project.destroy

	flash[:notice]="Project has been deleted"
	redirect_to projects_path
end

	private
		def project_params
			params.require(:project).permit(:name, :description)

		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(*parts)
		unless parts.empty?
				content_for :title do
					(parts << "Ticketee").join (" - ")
			end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
  <%if content_for?(:title) %>
  <%= yield(:title) %>
  <%else%>
  Ticketee
  <% end %> 	
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
<%= link_to "Ticketee", root_path, class: "navbar-brand" %>
<button type="button" class="navbar-toggle collapsed"
data-toggle="collapse" data-target="#collapse">
<span class="sr-only"> Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>

<div class="collapse navbar-collapse" id="collapse">
<ul class="nav navbar-nav">
<li class="<%= "active" if current_page?("/")%>">
<%=link_to "Home", root_path %>
</li>

<% unless user_signed_in?%> 
<li class="<%= "active" if current_page?("/users/sign_up") %>">
<%= link_to "Sign Up", new_user_registration_path %>
</li>
<li class="<%="active" if current_page?("/users/sign_in")%>">
  <%= link_to "Sign in", new_user_session_path %>
</li>
<%end%>
<% if user_signed_in? %>
<div class="navbar-right">
<p class="navbar-text">
  Signed in as: <%=current_user.email %>
</p>
<ul class="nav navbar-nav">
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
</ul>
</div>
<% end %>
</div>
</nav>

<div class="container">



<%= yield %>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%=simple_form_for(project) do |f| %>

<%= f.input :name%>
<%= f.input :description%>
<%= f.button :submit, class: "btn-primary" %>

<%end%>

<%if project.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(project.errors.count, "error") %>

prohibited this project from being saved:</h2>
<ul>
<% project.errors.full_messages.each do |msg| %>
<li><%=msg%></li>
<% end %>
</ul>
</div>
<%end%>

app/views/projects/edit.html.erb
<div class="page-header">
<h1>Editing projects</h1>
</div>

<%=render "form", project: @project%>

app/views/projects/index.html.erb
<div class="page-header">
<h1>
Projects
</h1>
<ul class="actions">
<li>
<%=link_to fa_icon("plus") + "New Projects", new_project_path,class: "btn btn-success" %>
</li>
</ul>
</div>


<div id="projects">

<% @projects.each do |project| %>
<h2> <%=link_to project.name, project%></h2>
<p><%=project.description%></p>

<% end %>
</div>

app/views/projects/new.html.erb
<div class="page-header">
<h1> New Project</h1>
</div>
<%= render "form", project: @project%>

app/views/projects/show.html.erb
<div class="page-header">
<h1>Showing Project Details</h1>
<ul class="actions">

<li><%=link_to "Edit Project", edit_project_path(@project), class: "new"%></li>
<li><%=link_to "Show all Projects",projects_path%></li>
<li><%=link_to "Delete Project", project_path(@project), method: :delete, class: "delete"%></li>
</ul>
</div>

Name and description of projects as follows:<br/>

Name:<%=@project.name%><br/>
Description: <%=@project.description%><br/>